# 配置端口
server:
  port: 9090
  servlet:
    context-path: /securityTemplate

# Security auth
auth:
  host:
    cors: http://localhost:8080,http://127.0.0.1:8080
  filter:
    enabled: false
    excludes: /api/auth/**
  security:
    verify: /api/auth/verify
    user: /api/resource/user/**
    admin: /api/resource/admin/**
    common: /api/auth/verify

spring:
  # MySQL 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    # 阿里连接池配置
    druid:
      initial-size: 5
      max-active: 30
      min-idle: 5
      max-wait: 10000
      # SQL防火墙
      filters: stat, wall
      # 配置监控选项，访问路径：http://localhost:9090/druid/
      web-stat-filter.enabled: true
      stat-view-servlet.enabled: true
      stat-view-servlet.login-username: admin
      stat-view-servlet.login-password: admin

# 绑定 MyBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: xyz.ibudai.entity
  # 控制台打印 sql 语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
