server:
  port: 9091
  servlet:
    context-path: /security3Template

spring:
  # MySQL 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.21:3306/db_security?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

# 认证配置
auth:
  expire:
    # Timeunit: minute
    jwt: 30
  host:
    # deploy to server need config to "*"
    cors: http://localhost:8080,http://127.0.0.1:8080
  filter:
    enabled: false
    whitelist: /api/sys/*,/api/open/**,/api/auth/ignored/*
  security:
    loginUrl: /api/sys/login
    logoutUrl: /api/sys/logout
    logoutSuccessUrl: /api/sys/logout/success
    ignoreUrls: /api/auth/ignored/*
    whitelist: /api/sys/*,/api/open/**
    userUrls: /api/user/**
    adminUrls: /api/admin/**

# 绑定 MyBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: xyz.ibudai.security.common.entity
  # 控制台打印 sql 语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
