server:
  port: 9091
  servlet:
    context-path: /security3Template

spring:
  # MySQL 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.21:3306/db_security?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

# 认证配置
auth:
  host:
    # deploy to server need config to "*"
    cors: http://localhost:8080,http://127.0.0.1:8080
  filter:
    enabled: true
    excludes: /api/auth/*
  security:
    loginUrl: /api/auth/login
    whitelist: /api/auth/register,/api/auth/forgot
    userUrls: /api/user/**
    adminUrls: /api/admin/**
    commonUrls: /api/free/**

# 绑定 MyBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: xyz.ibudai.security.common.entity
  # 控制台打印 sql 语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
